# Import libraries

In [1]:
from stat_sum_func import SplittedDatasetStatistics

# Splitted Data statistics summary

In [2]:
file = "3droad"

## Random_Split

In [3]:
train_path = f"splitted/{file}/Random_Split/train_0.parquet"
test_path = f"splitted/{file}/Random_Split/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

========================================Train data Samples========================================

              X1        X2       X3   target
0      -1.522200  1.248700  0.93864 -15.8090
1      -0.062097  0.388870  1.72680 -10.2980
2       0.059452  0.925230  0.40868  35.8420
3       0.844510 -0.621170  0.18112   6.5483
4       0.741760  0.360240 -1.12490  -1.4642
...          ...       ...      ...      ...
304406  1.349700  0.028330  0.73913 -12.7560
304407 -0.021434  0.907190  0.38837  70.1560
304408  0.798240 -0.061993 -0.60086  37.7790
304409 -1.425100  0.418090 -0.21082 -11.3810
304410 -1.864700  0.414520 -0.36037  28.2500

[304411 rows x 4 columns]

========================================Test data Samples========================================

              X1       X2        X3   target
0      -0.026622 -1.38020 -0.988030 -18.8280
1       0.978830 -2.51630 -1.632400 -20.8350
2      -1.918000  0.41818 -0.283440 -15.1660
3       0.077155 -0.64808 -0.092912   6.0770
4      -1.699700  0.23335 -0.945800  39.6220
...          ...      ...       ...      ...
130458  0.266820  0.10769  0.234710 -13.4980
130459  1.183200  0.48634  1.009700   3.3794
130460  0.068009  0.56842 -0.782690  30.8440
130461  0.274630  1.02690  0.246100 -11.1530
130462  1.163100 -1.72740 -0.249860  16.9220

[130463 rows x 4 columns]

In [4]:
statistics_man.print_stat_sum()

========================================Train data Statistics Summary========================================
Number of samples : 304411
Number of features: 3
==============================

,dtype,missing,count,median,mean,std,min,25%,50%,75%,max
X1,float64,0,304411.0,0.10886,-0.000589,0.999486,-2.4737,-0.402390,0.10886,0.74379,1.5859
X2,float64,0,304411.0,0.24640,-0.001214,1.000344,-2.5276,-0.629335,0.24640,0.70147,2.3392
X3,float64,0,304411.0,-0.14302,-0.000458,0.999950,-1.7316,-0.821905,-0.14302,0.77599,2.3033
target,float64,0,304411.0,-4.56320,0.015332,18.611448,-26.6830,-15.153000,-4.56320,9.66225,107.1000

========================================Test data Statistics Summary========================================
Number of samples : 130463
Number of features: 3
==============================

,dtype,missing,count,median,mean,std,min,25%,50%,75%,max
X1,float64,0,130463.0,0.10886,0.001375,1.001197,-2.4737,-0.401630,0.10886,0.745285,1.5859
X2,float64,0,130463.0,0.25000,0.002832,0.999196,-2.5268,-0.625675,0.25000,0.703995,2.3391
X3,float64,0,130463.0,-0.14140,0.001068,1.000120,-1.7293,-0.818790,-0.14140,0.778675,2.3029
target,float64,0,130463.0,-4.73550,-0.035772,18.633261,-30.7940,-15.169000,-4.73550,9.538100,112.2600

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()

## Covariate_Shift

In [ ]:
train_path = f"splitted/{file}/Covariate_Shift/train_0.parquet"
test_path = f"splitted/{file}/Covariate_Shift/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
statistics_man.plot_corr_heatmap()

## Mfs_based_Split

In [ ]:
train_path = f"splitted/{file}/Mfs_based_Split/train_1.parquet"
test_path = f"splitted/{file}/Mfs_based_Split/test_1.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()

## Single_Hyperball

In [ ]:
train_path = f"splitted/{file}/Random_Split/train_0.parquet"
test_path = f"splitted/{file}/Random_Split/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()

## Multiple_Hyperballs

In [ ]:
train_path = f"splitted/{file}/Multiple_Hyperballs/train_0.parquet"
test_path = f"splitted/{file}/Multiple_Hyperballs/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()

## KMeans_Hyperballs

In [ ]:
train_path = f"splitted/{file}/KMeans_Hyperballs/train_0.parquet"
test_path = f"splitted/{file}/KMeans_Hyperballs/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()

## Single_Slab

In [ ]:
train_path = f"splitted/{file}/Single_Slab/train_0.parquet"
test_path = f"splitted/{file}/Single_Slab/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()

## Semi_Infinite_Slab

In [ ]:
train_path = f"splitted/{file}/Semi_Infinite_Slab/train_0.parquet"
test_path = f"splitted/{file}/Semi_Infinite_Slab/test_0.parquet"

statistics_man = SplittedDatasetStatistics(train_path, test_path)

print("==" * 20 + "Train data Samples" + "==" * 20)
display(statistics_man.train.df)

print("==" * 20 + "Test data Samples" + "==" * 20)

display(statistics_man.test.df)

In [ ]:
statistics_man.print_stat_sum()

In [ ]:
statistics_man.plot_pairplot()

In [ ]:
for feature in statistics_man.df_all.columns[:-1]:
    statistics_man.plot_distribution(feature)

In [ ]:
statistics_man.plot_corr_heatmap()